# Generated by Django 5.0.1 on 2024-01-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_alter_flashcarddesafio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcarddesafio',
            name='user',
        ),
    ]
