# Generated by Django 5.0 on 2024-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostila', '0002_alter_apostila_arquivo_viewapostila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='apostila',
            name='tags',
            field=models.ManyToManyField(to='apostila.tags'),
        ),
    ]
